# This workflow will install Python dependencies and run unit tests for given OSes

name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: [ 3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework>=3.2.1
        pip install pylama pylama_pylint
        pip install coverage
    - name: Code quality with pylama
      run: pylama -o pylama.ini
      if: always()
    - name: Run unit tests with coverage
      run: python -m coverage run -m unittest discover
      if: always()
    - name: Codecov
      uses: codecov/codecov-action@v1.0.11
      with:
        name: ${{ matrix.python-version }}-${{ matrix.os }}
      if: always()
